
language: go

addons:
  chrome: stable

cache:
  directories:
  - $GOPATH

install:
- echo '8405d748b7b56720b004c18087576a24b7eab057725c03c8160b949d239c6ee4 go.mod'  | sha256sum -c || (rm go.tar.gz; wget -O go.tar.gz https://dl.google.com/go/go1.14.linux-amd64.tar.gz)
- tar -C ~ -xzf go.tar.gz
- export GOROOT=~/go
- export PATH=$GOROOT/bin:$PATH
- go version
- go env
- go get github.com/agnivade/wasmbrowsertest
- cp $GOPATH/bin/wasmbrowsertest $GOPATH/bin/go_js_wasm_exec

script:
- GOOS=js GOARCH=wasm go vet .
- GOOS=js GOARCH=wasm gofmt -l -s -w .
- GOOS=js GOARCH=wasm go test -exec wasmbrowsertest -v -x .