
language: go

env:
- GO111MODULE=on

go:
- 1.12.x
- 1.13.x
- tip

addons:
  chrome: stable

install:
- go get github.com/agnivade/wasmbrowsertest
- mv $GOPATH/bin/wasmbrowsertest $GOPATH/bin/go_js_wasm_exec
- export PATH=$GOPATH/bin:$PATH

script:
- GOOS=js GOARCH=wasm go test -v .  
- go vet .
- gofmt -l -s -w .